version: "3.8"
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MpServer #optional (specify default database instead of $POSTGRES_USER)
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  # CREATE USER root WITH PASSWORD = 'root'
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: